#pragma once

#include "MathTypes.h"

RIFT_API CONST_ATTRIB NO_DISCARD f32 Sqrt(f32 X);
RIFT_API CONST_ATTRIB NO_DISCARD f32 Pow(f32 X, f32 Y);
RIFT_API CONST_ATTRIB NO_DISCARD f64 Powd(f64 X, f64 Y);
RIFT_API CONST_ATTRIB NO_DISCARD f32 Exp(f32 X);

RIFT_API CONST_ATTRIB NO_DISCARD f32 Abs(f32 Value);
RIFT_API CONST_ATTRIB NO_DISCARD f64 Absf64(f64 Value);
RIFT_API CONST_ATTRIB NO_DISCARD i32 Absi32(i32 Value);
RIFT_API CONST_ATTRIB NO_DISCARD i64 Absi64(i64 Value);
