    // X("Hash",             Test_HashUtils_FNV1a_Basic)
    // X("Hash",             Test_HashUtils_PointerHash)

    X("HashTable",        Test_HashTable_AddAndFind) \
    X("HashTable",        Test_HashTable_FindMissing) \
    X("HashTable",        Test_HashTable_UpdateExisting) \
    X("HashTable",        Test_HashTable_GrowOnLoad) \
    X("HashTable",        Test_HashTable_DestroyCleanup) \

#define TEST_LIST \
    X("Linear Allocator", Test_LinearAllocator_CreateAndDestroy) \
    X("Linear Allocator", Test_LinearAllocator_SingleAllocationAllSpace) \
    X("Linear Allocator", Test_LinearAllocator_MultiAllocationAllSpace) \
    X("Linear Allocator", Test_LinearAllocator_MultiAllocationAllSpaceThenFree) \
    X("String",           Test_StringUtils_Create) \
    X("String",           Test_StringUtils_Reserve) \
    X("String",           Test_StringUtils_Append) \
    X("String",           Test_StringUtils_Format) \
    X("String",           Test_StringUtils_BuildPath) \
    X("String",           Test_StringUtils_BuildSeparator) \
    X("String",           Test_StringUtils_Empty) \
    X("String",           Test_StringUtils_Fill) \
    X("String",           Test_StringUtils_ToUpper) \
    X("String",           Test_StringUtils_ToLower) \
    X("String",           Test_StringUtils_ToNarrow) \
    X("String",           Test_StringUtils_ToWide) \
    X("String",           Test_StringUtils_BackSlashToForwardSlash) \
    X("String",           Test_StringUtils_FrontSlashToBackSlash) \
    X("String",           Test_StringUtils_EatSpaces) \
    X("String",           Test_StringUtils_EatPathSeparators) \
    X("String",           Test_StringUtils_IndexOfChar) \
    X("String",           Test_StringUtils_IndexOfWhitespace) \
    X("String",           Test_StringUtils_CountChar) \
    X("String",           Test_StringUtils_CountSpaces) \
    X("String",           Test_StringUtils_CountPathSeparators) \
    X("String",           Test_StringUtils_ParseIntoArray) \
    X("String",           Test_StringUtils_GetLength) \
    X("String",           Test_StringUtils_GetLengthFast) \
    X("String",           Test_StringUtils_IsAlphabetUpper) \
    X("String",           Test_StringUtils_IsAlphabetLower) \
    X("String",           Test_StringUtils_IsAlphabet) \
    X("String",           Test_StringUtils_IsDigit) \
    X("String",           Test_StringUtils_IsWhitespace) \
    X("String",           Test_StringUtils_IsNewline) \
    X("String",           Test_StringUtils_IsSymbol) \
    X("String",           Test_StringUtils_CheckEquality_CaseSensitive) \
    X("String",           Test_StringUtils_CheckEquality_CaseInsensitive) \
    X("String",           Test_StringUtils_CheckInequality_CaseSensitive) \
    X("String",           Test_StringUtils_CheckInequality_CaseInsensitive) \
    X("String",           Test_StringUtils_CheckEquality_Empty) \
    X("String",           Test_StringUtils_IsValid) \
    X("String",           Test_StringUtils_StartsWith) \
    X("String",           Test_StringUtils_EndsWith) \
    X("String",           Test_StringUtils_Contains) \
    X("String",           Test_StringUtils_ToU8) \
    X("String",           Test_StringUtils_ToU16) \
    X("String",           Test_StringUtils_ToU32) \
    X("String",           Test_StringUtils_ToU64) \
    X("String",           Test_StringUtils_ToI8) \
    X("String",           Test_StringUtils_ToI16) \
    X("String",           Test_StringUtils_ToI32) \
    X("String",           Test_StringUtils_ToI64) \
    X("String",           Test_StringUtils_ToF32) \
    X("String",           Test_StringUtils_ToF64) \
    X("String",           Test_StringUtils_ToBool) \
    X("Platform",         Test_PlatformUtils_GetWorkingDirectory) \
    X("Filesystem",       Test_FilesystemUtils_GetFilePath) \
    X("Filesystem",       Test_Filesystem_DoesPathHaveFileExtension) \
    X("Filesystem",       Test_Filesystem_ExtractFilePath_WithSlash) \
    X("Filesystem",       Test_Filesystem_ExtractFilePath_WithoutSlash) \
    X("Filesystem",       Test_Filesystem_ExtractFileName_WithExtension) \
    X("Filesystem",       Test_Filesystem_ExtractFileName_WithoutExtension) \
    X("Filesystem",       Test_Filesystem_StripFileExtension) \
    X("Filesystem",       Test_Filesystem_ExtractFileExtension_WithDot) \
    X("Filesystem",       Test_Filesystem_ExtractFileExtension_WithoutDot) \
    X("Filesystem",       Test_Filesystem_IsPathRelative) \
    X("Filesystem",       Test_Filesystem_ArePathsCommon) \
    X("Filesystem",       Test_Filesystem_AppendExeExtension) \
    X("Filesystem",       Test_Filesystem_NewFile_DeleteFile_DoesExist) \
    X("Filesystem",       Test_Filesystem_DoesDirectoryExist) \
    X("Filesystem",       Test_Filesystem_OpenWriteReadClose) \
    X("Filesystem",       Test_Filesystem_GetFileSize) \
    X("Filesystem",       Test_Filesystem_SeekOperations) \
    X("Filesystem",       Test_Filesystem_IsNewerIsOlder) \
    X("Filesystem",       Test_Filesystem_CopyFile) \
    X("Filesystem",       Test_Filesystem_MoveFile) \
    X("Filesystem",       Test_Filesystem_WriteLine) \
    X("Filesystem",       Test_Filesystem_MemoryMapped) \
    X("Filesystem",       Test_Filesystem_OpenDirectory) \
    X("Filesystem",       Test_Filesystem_OpenDirectory_Ex) \
    X("Filesystem",       Test_Filesystem_Seek_Relative) \
    X("Filesystem",       Test_Filesystem_SeekFromEnd) \
    X("Filesystem",       Test_Filesystem_GetTimes_ByPath) \
    X("Filesystem",       Test_Filesystem_GetTimes_ByHandle) \
    X("Filesystem",       Test_Filesystem_GetFileTime_ByPath) \
    X("Filesystem",       Test_Filesystem_GetFileTime_ByHandle) \
    X("Filesystem",       Test_Filesystem_ReadEntireFile) \
    X("Filesystem",       Test_Filesystem_ReadLine) \
    X("Filesystem",       Test_Filesystem_WriteLineFormatted) \
    X("Filesystem",       Test_Filesystem_IsFile) \
    X("Filesystem",       Test_Filesystem_IsDirectory) \
    X("Filesystem",       Test_Filesystem_ConvertRelativeToAbsolutePath) \
    X("Filesystem",       Test_Filesystem_IterateDirectory) \
    X("Filesystem",       Test_Filesystem_IterateDirectory_Ex) \
    X("Filesystem",       Test_Filesystem_DeleteFiles) \
    X("Filesystem",       Test_Filesystem_DeleteDirectory) \
    X("Filesystem",       Test_Filesystem_IsValidFileHandle) \
    X("Math",             Test_MathUtils_Abs) \
    X("Math",             Test_MathUtils_Absf64) \
    X("Math",             Test_MathUtils_Absi32) \
    X("Math",             Test_MathUtils_Absi64) \
    X("Math",             Test_MathUtils_MinMax) \
    X("Math",             Test_MathUtils_Clamp) \
    X("Math",             Test_MathUtils_ClampF64) \
    X("Math",             Test_MathUtils_MinMaxF64) \
    X("Memory",           Test_Memory_MemSetAndMemZero) \
    X("Memory",           Test_Memory_MemCopy) \
    X("Memory",           Test_Memory_MemMove) \
    X("Memory",           Test_Memory_MemEqual) \
    X("Array",            Test_ArrayUtils_CreateAndDestroy) \
    X("Array",            Test_ArrayUtils_AddAndAccess) \
    X("Array",            Test_ArrayUtils_Reserve) \
    X("Array",            Test_ArrayUtils_EmptyAndSetNum) \
    X("Array",            Test_ArrayUtils_Last) \
    X("Array",            Test_ArrayUtils_RemoveLast) \
    X("Array",            Test_ArrayUtils_RemoveAt) \
    X("Array",            Test_ArrayUtils_InsertAt) \
    X("String",           Test_StringUtils_IsInteger) \
    X("String",           Test_StringUtils_IsFloat) \
    X("String",           Test_StringUtils_IsNumeric) \
    X("String",           Test_StringUtils_Duplicate) \
    X("String",           Test_StringUtils_Left) \
    X("String",           Test_StringUtils_Right) \
    X("String",           Test_StringUtils_IndexOfLastChar) \
    X("String",           Test_StringUtils_TrimQuotes) \
    X("String",           Test_StringUtils_IsFirst) \
    X("String",           Test_StringUtils_IsLast) \
    X("String",           Test_StringUtils_FromI32) \
    X("String",           Test_StringUtils_FromU32) \
    X("String",           Test_StringUtils_CompareVersion) \
    X("String",           Test_StringUtils_Integer_CountDigits) \
    X("String",           Test_StringUtils_ContainsDigits) \
    X("String",           Test_StringUtils_ReplaceCharInline) \
    X("String",           Test_StringUtils_ContainsPathSeparators) \
    X("String",           Test_StringUtils_FromI64) \
    X("String",           Test_StringUtils_FromU64) \
    X("String",           Test_StringUtils_Copy) \
    X("String",           Test_StringUtils_AppendChar) \
    X("String",           Test_StringUtils_IndexOfSubstring) \
    X("String",           Test_StringUtils_StripWhitespace) \
    X("String",           Test_StringUtils_EatSpacesFromEnd) \
