name: Build (Windows/MacOS/Linux)
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.github/**'

jobs:
  RunOnUbuntu:
    name: Build RiftBuild (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build_unix.sh
  
  RunOnWindows:
    name: Build RiftBuild (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: build_windows.bat
  
  RunOnMacOS:
    name: Build RiftBuild (Mac OS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build_unix.sh
